dir=D:\Softwares\mpv-v0.41.0-x86_64-pc-windows-msvc\thumb_cache
quit_after_inactivity=30
tone_mapping=no

# Maximum thumbnail size (matches ModernZ's high-res scaling)
max_height=240
max_width=240

# Allow hardware decoding for the thumbnail generation (makes it much faster)
hwdec=yes

# Allow thumbnails for network streams / YouTube videos
network=yes

# Spawn the background worker without waiting
spawn_first=yes

# The exact path to the executable file
mpv_path=D:\Softwares\mpv-v0.41.0-x86_64-pc-windows-msvc\mpv.exe